name: aurabajar
description: "A shopping app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  carousel_slider: ^5.1.2
  intl: ^0.20.2


  cupertino_icons: ^1.0.8
  easy_stepper: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true